# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f8d6d24ce68f5a5a504914b4b043a8c7"
application_url = "https://example.com"
embedded = true
name = "lm-fomo"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products,write_metafields"

[webhooks]
api_version = "2026-01"
[[webhooks.subscriptions]]
topics = [ "orders/create", "app/uninstalled" ]
uri = "/api/webhooks"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
